name: knocky
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.3+76

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bbob_dart: 0.1.1
  get: 4.6.5
  dio: 4.0.6
  cached_network_image: 3.2.3
  timeago: 3.3.0
  intl: 0.17.0
  get_storage: 2.0.3
  font_awesome_flutter: 10.3.0
  numberpicker: 2.1.1
  time_formatter: 1.0.0+5
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  scrollable_positioned_list: 0.3.5
  url_launcher: 6.1.8
  after_layout: 1.2.0
  measure_size: 4.0.0
  gallery_saver: 2.3.2
  share: 2.0.4
  permission_handler: 10.2.0
  matrix4_transform: 2.0.1
  duration: 3.0.12
  tweet_ui: 4.0.4
  better_player: 0.0.83
  flutter_dotenv: 5.0.2
  popover: 0.2.8
  flutter_barcode_scanner: 2.0.0
  sticky_headers: 0.3.0+2
  event_bus: 2.0.0
  package_info_plus: 3.0.2
  optimized_cached_image: 3.0.1
  image_picker: 0.8.6+1
  flutter_svg: 1.1.6
  uni_links: 0.5.1
  flutter_custom_tabs: 1.0.4
  layout: 
    git: https://github.com/chirag729/layout.git
  extended_image: 6.3.4

dependency_overrides:
  #visibility_detector: 0.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
  - assets/.env
  - assets/logo.png
  - assets/icons.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf